### ISSUE TITLE
y u no varints

### ISSUE THREAD

**Issue by daviddias** [jbenet/go-msgio#13]
msgio is using 4 byte (Unsigned uint32, network byte order) for length prefixing instead of a varint  :(

https://github.com/jbenet/go-msgio/blob/master/msgio.go#L15

This goes against the msgio/lpm-stream spec defined inside the multistream spec - https://github.com/multiformats/multistream/tree/master/lpm-stream

**Comment by whyrusleeping** [comment]
https://github.com/jbenet/go-msgio/blob/master/varint.go

**Comment by daviddias** [comment]
@whyrusleeping got it. So msgio can do it all and unfortunately secio does 4 byte prefix
